version: "3"
services:
  api:
    build:
      context: ./team-up-server
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    container_name: team-up-server
    networks:
      - mern-stack-net

  redis_db:
    image: redis:latest
    container_name: redis_db
    restart: always
    networks:
      - mern-stack-net
    ports:
      - 6379:6379

networks:
  mern-stack-net:
    driver: bridge
